# Job to run a Ray program in its own pod. Assumes that a cluster is already
# running (e.g., from './ray-cluster.yaml').
apiVersion: batch/v1
kind: Job
metadata:
  namespace: ray
  generateName: graphity-test-job-
spec:
  template:
    spec:
      restartPolicy: Never          
      imagePullSecrets:
        - name: gitlab-reg
      containers:
        - name: ray-head
          image: registry.gitlab.com/graphity/graphity:v0.3.1.10
          imagePullPolicy: IfNotPresent
          command: [ "/bin/bash", "-c", "--" ]
          args:
            - "
              ray start --node-ip-address=$MY_POD_IP --num-cpus=0 --address=$GRAPHITY_HEAD_SERVICE_HOST:$GRAPHITY_HEAD_SERVICE_PORT_REDIS_PRIMARY --object-manager-port=12345 --node-manager-port=12346 &&
              python /graphity/source/anneal/main.py"
          ports:
            - containerPort: 12345 # Ray internal communication.
            - containerPort: 12346 # Ray internal communication.
          env:
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
