image: python:3.8

stages:
  - Build Library
  - Test
  - Deploy 
#########
# Build the boost / python dependencies of out project.
# All jobs use GIT_LFS_SKIP_SMUDGE, which prevents GIT LFS from pulling large data files.
#########
Build Dependencies:
  stage: Build Library
  needs: []
  script:
    - python3 --version
    - pip3 install -r requirements.txt
    - pip3 install -e .

Run Tests:
  stage: Test
  needs: [Build Dependencies]
  artifacts:
    paths:
      - artifacts/*
      - artifacts/**
    expire_in: 1 week
  script:
    - pip3 install -r requirements.txt
    - pip3 install -e .
    - python3 -m pytest .

pages:
  stage: Deploy
  needs: []
  artifacts:
    paths:
      - public
  script:
  - pip install -r requirements.txt
  - cd docs && make html && mv build/html ../public
  only:
    - master

