image: python:3.9

stages:
  - Build Library
  - Test
#########
# Build the boost / python dependencies of out project.
# All jobs use GIT_LFS_SKIP_SMUDGE, which prevents GIT LFS from pulling large data files.
#########
Build Dependencies:
  stage: Build Library
  needs: []
  script:
    - pip3 install -r requirements.txt
    - pip3 install -e .

Run Tests:
  stage: Test
  needs: [Build Dependencies]
  script:
    - pip3 install -r requirements.txt
    - pip3 install -e .
    - python3 -m pytest .
    